#!/bin/sh
#$ -cwd
#$ -N OS_runs
swan_omp_exe=/p/1230058-os/swanmodel/SWANNC8/swan.exe
export LD_LIBRARY_PATH=/p/1230058-os/swanmodel/SWANNC8/
export OMP_NUM_THREADS=8

echo ----------------------------------------------------------------------
echo $swan_omp_exe
echo with OpenMP on linux cluster.
echo SGE_O_WORKDIR : $SGE_O_WORKDIR
echo HOSTNAME : $HOSTNAME
echo OMP_NUM_THREADS : $OMP_NUM_THREADS
echo $1
echo ----------------------------------------------------------------------

### General, start SWAN.

cp "$1".SWN INPUT
starttime=`date +%s`
$swan_omp_exe
endtime=`date +%s`

runtime=$((endtime-starttime))
echo ----------------------------------------------------------------------
echo $runtime
echo ----------------------------------------------------------------------

cp PRINT "$1".PRT
rm INPUT
rm PRINT
rm swaninit
rm norm_end

source /opt/python/pythonsource.sh
source /p/1230058-os/virtualenvs/oosterschelde/bin/activate
wavetrans $1_01.SP2 /p/1230058-os/swanmodel/TEST01/INPVAR/RVW/

cd ../$2

cp "$2".SWN INPUT
starttime=`date +%s`
$swan_omp_exe
endtime=`date +%s`

runtime=$((endtime-starttime))
echo ----------------------------------------------------------------------
echo $runtime
echo ----------------------------------------------------------------------

cp PRINT "$2".PRT

rm INPUT
rm PRINT
rm swaninit
rm norm_end



